# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm_embed.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fllm_embed.proto\x12\x17languagemodelembeddings"\x1b\n\tSentences\x12\x0e\n\x06inputs\x18\x01'
    b' \x03(\t"\x1c\n\tEmbedding\x12\x0f\n\x07\x66\x65\x61ture\x18\x01'
    b' \x03(\x02"I\n\x10ListOfEmbeddings\x12\x35\n\tembedding\x18\x01'
    b' \x03(\x0b\x32".languagemodelembeddings.Embedding2i\n\rLanguageModel\x12X\n\x05\x45mbed\x12".languagemodelembeddings.Sentences\x1a).languagemodelembeddings.ListOfEmbeddings"\x00\x42:\n\x16io.grpc.examples.embedB\x16LanguageModelEmbeddingP\x01\xa2\x02\x05\x65mbedb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "llm_embed_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\026io.grpc.examples.embedB\026LanguageModelEmbeddingP\001\242\002\005embed"
    )
    _SENTENCES._serialized_start = 44
    _SENTENCES._serialized_end = 71
    _EMBEDDING._serialized_start = 73
    _EMBEDDING._serialized_end = 101
    _LISTOFEMBEDDINGS._serialized_start = 103
    _LISTOFEMBEDDINGS._serialized_end = 176
    _LANGUAGEMODEL._serialized_start = 178
    _LANGUAGEMODEL._serialized_end = 283
# @@protoc_insertion_point(module_scope)
