# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm_chat.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0ellm_chat.proto\x12\x11languagemodelchat\x1a\x1cgoogle/protobuf/struct.proto"\xe3\x01\n\x0c\x43hatLogInput\x12)\n\x08messages\x18\x01'
    b" \x03(\x0b\x32\x17.languagemodelchat.Chat\x12\x12\n\nmax_tokens\x18\x02"
    b" \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\r\n\x05top_p\x18\x04"
    b" \x01(\x02\x12\t\n\x01n\x18\x05 \x01(\x05\x12\x0e\n\x06stream\x18\x06"
    b" \x01(\x08\x12\x0c\n\x04stop\x18\x07 \x01(\t\x12\x18\n\x10presence_penalty\x18\x08"
    b" \x01(\x02\x12\x19\n\x11\x66requence_penalty\x18\t \x01(\x02\x12\x12\n\nlogit_bias\x18\n"
    b' \x01(\t":\n\rChatLogOutput\x12)\n\x08messages\x18\x01'
    b' \x03(\x0b\x32\x17.languagemodelchat.Chat"\\\n\x04\x43hat\x12\x11\n\x04role\x18\x01'
    b" \x01(\tH\x00\x88\x01\x01\x12,\n\x07\x63ontent\x18\x02"
    b" \x01(\x0b\x32\x16.google.protobuf.ValueH\x01\x88\x01\x01\x42\x07\n\x05_roleB\n\n\x08_content2\xad\x01\n\rLanguageModel\x12K\n\x04\x43hat\x12\x1f.languagemodelchat.ChatLogInput\x1a"
    b' .languagemodelchat.ChatLogOutput"\x00\x12O\n\x06Stream\x12\x1f.languagemodelchat.ChatLogInput\x1a'
    b' .languagemodelchat.ChatLogOutput"\x00\x30\x01\x42\x33\n\x15io.grpc.examples.chatB\x11LanguageModelChatP\x01\xa2\x02\x04\x63hatb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "llm_chat_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n\025io.grpc.examples.chatB\021LanguageModelChatP\001\242\002\004chat"
    )
    _globals["_CHATLOGINPUT"]._serialized_start = 68
    _globals["_CHATLOGINPUT"]._serialized_end = 295
    _globals["_CHATLOGOUTPUT"]._serialized_start = 297
    _globals["_CHATLOGOUTPUT"]._serialized_end = 355
    _globals["_CHAT"]._serialized_start = 357
    _globals["_CHAT"]._serialized_end = 449
    _globals["_LANGUAGEMODEL"]._serialized_start = 452
    _globals["_LANGUAGEMODEL"]._serialized_end = 625
# @@protoc_insertion_point(module_scope)
