# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tllm.proto\x12\rlanguagemodel"\x84\x02\n\x07Message\x12\x0e\n\x06prompt\x18\x01'
    b" \x01(\t\x12\x0e\n\x06suffix\x18\x02 \x01(\t\x12\x12\n\nmax_tokens\x18\x03"
    b" \x01(\x05\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\x12\r\n\x05top_p\x18\x05"
    b" \x01(\x02\x12\t\n\x01n\x18\x06 \x01(\x05\x12\x0e\n\x06stream\x18\x07"
    b" \x01(\x08\x12\x10\n\x08logprobs\x18\x08 \x01(\x05\x12\x0c\n\x04\x65\x63ho\x18\t"
    b" \x01(\x08\x12\x0c\n\x04stop\x18\n \x01(\t\x12\x18\n\x10presence_penalty\x18\x0b"
    b" \x01(\x02\x12\x19\n\x11\x66requence_penalty\x18\x0c"
    b" \x01(\x02\x12\x0f\n\x07\x62\x65st_of\x18\r \x01(\x05\x12\x12\n\nlogit_bias\x18\x0e"
    b' \x01(\t"\x1c\n\x0b\x43ompletions\x12\r\n\x05reply\x18\x01'
    b' \x01(\t2\x9b\x01\n\rLanguageModel\x12@\n\x08\x43omplete\x12\x16.languagemodel.Message\x1a\x1a.languagemodel.Completions"\x00\x12H\n\x0eStreamComplete\x12\x16.languagemodel.Message\x1a\x1a.languagemodel.Completions"\x00\x30\x01\x42+\n\x13io.grpc.examples.lmB\rLanguageModelP\x01\xa2\x02\x02LMb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "llm_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\023io.grpc.examples.lmB\rLanguageModelP\001\242\002\002LM"
    _MESSAGE._serialized_start = 29
    _MESSAGE._serialized_end = 289
    _COMPLETIONS._serialized_start = 291
    _COMPLETIONS._serialized_end = 319
    _LANGUAGEMODEL._serialized_start = 322
    _LANGUAGEMODEL._serialized_end = 477
# @@protoc_insertion_point(module_scope)
